-- Query testing on PSF data

SELECT * FROM CASES
LIMIT 1000;

SELECT * FROM PARTICIPANTS
LIMIT 1000;

SELECT * FROM PLACEMENTS
LIMIT 100;

SELECT * FROM REMOVALS
LIMIT 100;

SELECT CASEID, ParticipantID, RecordYear, Gender, CASES.INTERNALCASEID, 
		CASEOPENDATE, CASECLOSEDATE, AdoptionFlag, RemovalManner, 
		Service, EpisodeType, PlacementSetting, EndingPurpose,
		EndReason
FROM CASES
INNER JOIN PARTICIPANTS USING (InternalCaseID)
INNER JOIN REMOVALS USING (IdentificationID)
INNER JOIN PLACEMENTS USING (IdentificationID);