-- Query testing on PSF data

SELECT * FROM CASES
LIMIT 1000;

SELECT * FROM PARTICIPANTS
LIMIT 1000;

SELECT * FROM PLACEMENTS
LIMIT 100;

SELECT * FROM REMOVALS
LIMIT 100;

SELECT CASEID, INTERNALCASEID, CASEOPENDATE, CASECLOSEDATE
FROM CASES;